# Generated by Django 4.1 on 2022-08-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creator",
            options={"ordering": ["first_name"]},
        ),
    ]
