# Generated by Django 4.1.1 on 2022-09-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_gazeteci"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makale",
            name="yazar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="makaleler",
                to="news.gazeteci",
            ),
        ),
    ]
