# Generated by Django 4.1 on 2022-08-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fscohort", "0003_student_country_student_registered_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="update_date",
            new_name="updated_date",
        ),
        migrations.AlterField(
            model_name="student",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Hakkında"),
        ),
    ]
